apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: k8s-demo
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/k8sdemo?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: demo
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
